import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Startup Sphere | ITE MAIT",
  description: "Welcome to the Startup Sphere Society at ITE MAIT College – your gateway to entrepreneurial success. We nurture, empower, and accelerate startups with resources, mentorship, and networking.",
  keywords: [
    "Startup Sphere",
    "MAIT",
    "ITE",
    "entrepreneurship",
    "innovation",
    "startups",
    "Maharaja Agrasen Institute of Technology",
    "reactjs",
    "nextjs",
    "react",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Startup Sphere",
    url: "https://www.linkedin.com/company/startups-sphere/",
  },
} as const;
